--- #YAML:1.0
name:               PNI-GUI-Tk
version:            0.12
abstract:           Perl Node Interface GUI, implemented with Tk
author:
    - G. Casati <fibo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PNI::Core:       0.03
    PNI::Node::Tk:   0.14
    Tk::MatchEntry:  0.4
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
